<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemOptimizerHub.Abstractions\SystemOptimizerHub.Abstractions.csproj" />
    <ProjectReference Include="..\SystemOptimizerHub.Core\SystemOptimizerHub.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
